language: c
matrix:
 include:
    - os: osx
      compiler: clang
      osx_image: xcode7.3
    - os: linux
      dist: trusty
      compiler: gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - make
  - make clean  
  - make check
after_success:
  - coveralls --exclude Unity --exclude tests --gcov-options '\-lp'
notifications:
  email:
    - haile_jiang@163.com