language: c
before_install:
  - pip install --user cpp-coveralls
script:
  - make
  - make clean  
  - make check
after_success:
  - coveralls --exclude Unity --exclude tests --gcov-options '\-lp'